server.port: 8085
logging.level.org.springframework.cloud.sleuth: DEBUG


spring:
  application:
    name: service5

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.application_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://127.0.0.1:8761}/eureka/
      

security:
  basic:
    enabled: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false


troublemaker.client.token: abc123

# management.health.binders.enabled: true

# endpoints.health.sensitive: false
management.security.enabled: false

spring.sleuth.sampler.percentage: 1.0
spring.sleuth.web.skipPattern: (^cleanup.*|.+favicon.*|^service*)