key1: value1-2
key2: value2
#foo: application-foo
spring.cloud.deployer.cloudfoundry:
  url: api.system.pcfdemo.net
  org: korea
  space: development
  username: mkim@pivotal.io
  password: changeme
spring.cloud.deployer.cloudfoundry.url: api.system.pcfdemo.net
