server.port: 8084
logging.level.org.springframework.cloud.sleuth: DEBUG


spring:
  application:
    name: service4

management.security.enabled: false
security:
  basic.enabled: false

#security.user.password: password

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    leaseRenewalIntervalInSecond: 3
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
spring.sleuth.sampler.percentage: 0.0